2D Tensor = |t| = batch size * dim   (세로 * 가로)  (64*256)

3D Tensor = |t| = batch size * width * height (Typical Computer Vision)

3D Tensor = |t| = batch size * length * dim (Typical Natural Language Processing)

In [3]:
import numpy as np

1D Array with NumPy

In [4]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [6]:
print('Rank of t: ',t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [12]:
print('t[0] t[1] t[-1]=',t[0],t[1],t[-1])
print('t[2:5] t[4:-1]= ',t[2:5],t[4:-1])
print ('t[:2] t[3:]= ',t[:2], t[3:])

t[0] t[1] t[-1]= 0.0 1.0 6.0
t[2:5] t[4:-1]=  [2. 3. 4.] [4. 5.]
t[:2] t[3:]=  [0. 1.] [3. 4. 5. 6.]


2D Array with NumPy

In [15]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [17]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)
