In [2]:
import numpy as np

test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [7]:
# 사이킷런 에서 사욜할 수 있도록 vector -> matrix 로 reshape 할때 사용
np.array(test_matrix).reshape(2,2,2)


array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [8]:
# -1 : size 기반으로 row 개수 선정 ex) 데이터 갯수가 100일때 size를 2로 설정 한다면, row는 50개
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [10]:
test = np.array(test_matrix).reshape(8, )
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [11]:
test.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [5],
       [8]])

flatten

In [25]:
# flatten : 다차원 array -> 1차원 array
test_matrix3 = [[[1, 2, 3, 4], [1, 2, 5, 8]], [[5, 4, 3, 2],[2,3,4,5]]]
np.array(test_matrix3).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 5, 4, 3, 2, 2, 3, 4, 5])