Indexing

In [1]:
import numpy as np

a= np.array([[1,2,3],[4,5,6]],int)
print(a)
print(a[0,0])
print(a[0][0])


[[1 2 3]
 [4 5 6]]
1
1


Slicing

In [8]:
a= np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
print(a[:,2:],"\n")  # 전체 row의 2열 이상
print(a[1,1:3],"\n")    # 1row 의 1~2열
print(a[1:3])  #1row ~ 2row 전체

[[ 3  4  5]
 [ 8  9 10]] 

[7 8] 

[[ 6  7  8  9 10]]


Arange : array의 범위를 지정하여 값의 list를 생성함.

In [12]:
np.arange(30).reshape(-1,5)  #0~29까지를 5개 열로 나누어 배열

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])