Indexing

In [1]:
import numpy as np

a= np.array([[1,2,3],[4,5,6]],int)
print(a)
print(a[0,0])
print(a[0][0])


[[1 2 3]
 [4 5 6]]
1
1


Slicing

In [2]:
a= np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
print(a[:,2:],"\n")  # 전체 row의 2열 이상
print(a[1,1:3],"\n")    # 1row 의 1~2열
print(a[1:3])  #1row ~ 2row 전체

[[ 3  4  5]
 [ 8  9 10]] 

[7 8] 

[[ 6  7  8  9 10]]


Arange : array의 범위를 지정하여 값의 list를 생성함.

In [3]:
np.arange(30).reshape(-1,5)  #0~29까지를 5개 열로 나누어 배열

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

zeros : 0으로 가득찬 ndarray 생성

ones : 1 로 가득찬 ndarray 생성


In [8]:
np.zeros(shape=(10,), dtype=np.int8) # 10 - zoro vector 생성


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [9]:
np.zeros((2, 5))  # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [11]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

something_like : 기존 ndarray의 shape 크기만큼 1,0 또는 empty array 반환

In [13]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

identity : 단위 행렬(i 행렬) 생성함

In [15]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

eye : 대각선이 1인 행렬, k값 시작 index의 변경 가능

In [17]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3,5,k=2,dtype=np.int8)   # k = start index

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

diag : 대각 행렬의 값 추출

In [21]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [23]:
np.diag(matrix, k=1)    # k = start index

array([1, 5])