All & Any : array의 데이터 전부(and) 또는 일부(or)가 조건에 만족 여부 반환

In [1]:
import numpy as np

In [2]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [4]:
np.any(a>5), np.any(a<0)   #하나라도 조건을 만족한다면 true

(True, False)

In [5]:
np.all(a > 5), np.all(a < 10)

(False, True)

comperision operation( 별로 안중요함)

In [7]:
a=np.array([1,3,0],float)
np.logical_and(a>0,a<3)

array([ True, False, False])

In [9]:
b=np.array([True,False,True],bool)
np.logical_not(b)       #NOT 조건의 condition

array([False,  True, False])

In [10]:
c=np.array([False,True,False],bool)
np.logical_or(b,c)      #OR 조건의 condition

array([ True,  True,  True])

(!중요!)np.where  : ndarray에서 조건에 맞는 값의 index를 찾아줌

In [14]:
a

array([1., 3., 0.])

In [12]:
np.where(a>0,3,2) #where(condition,TRUE, FALSE)

array([3, 3, 2])

In [15]:
a=np.arange(5,15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.where(a>10)

(array([6, 7, 8, 9], dtype=int64),)

(!중요!)argmax & argmin : 최대나 최소의 index 반환

In [18]:
a=np.array([1,2,4,5,8,89,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

axis 기반의 반환

In [23]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
print(a)
np.argmax(a, axis=1), np.argmin(a, axis=0)

[[ 1  2  4  7]
 [ 9 88  6 45]
 [ 9 76  3  4]]


(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))