벡터(vector) : 숫자를 원소로 가지는 list(array)

In [11]:
import numpy as np
x=np.array([1,7,3])
y=np.array([5,2,1])

print(x+y)
print(x-y)
print(x*y)


[6 9 4]
[-4  5  2]
[ 5 14  3]


벡터의 노름(norm) : 원점에서부터의 거리
||X||

L1 노름 : 마름모 모양(Robust학습, Lasso회귀)

L2 노름 : 원 모양
(Laplace근사, Ridge회귀)



두 벡터 사이의 각도 : 제2코사인 법칙(내적)

In [12]:
def l1_norm(x):
    x_norm=np.abs(x)
    x_norm=np.sum(x_norm)
    return x_norm

def l2_norm(x):
    x_norm = x*x
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)
    return x_norm

def angle(x,y):
    v=np.inner(x,y) / (l2_norm(x)*l2_norm(y))
    theta = np.arccos(v)
    return theta

angle(x,y)

1.0205221433446645